FROM  busybox

MAINTAINER bbytes  "info@beyondbytes.co.in"

# RUN-USING:  docker run -name NAME cloudezz/data

# NOTE: Create base folders
RUN mkdir -p /cloudezz
RUN mkdir -p /cloudezz/app
RUN mkdir -p /cloudezz/data

CMD ["/bin/true"]
